### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by sageworksstudio** [silverstripe/silverstripe-routewhitelist#3]
Per instructions:
`composer require silverstripe/route-whitelist:*`

Composer returns this error:

```
Problem 1
    - The requested package silverstripe/route-whitelist could not be found in any version, there may be a typo in the package name.
```

**Comment by sageworksstudio** [comment]
Instructions should say:
`composer require silverstripe/routewhitelist:*`
Note the removal of the dash in `routewhitelist`.

**Comment by candidasa** [comment]
Fixed
